# Generated by Django 2.1.4 on 2018-12-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instvol', '0004_auto_20181224_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
    ]
